### ISSUE TITLE
'data' folder is missing

### ISSUE THREAD

**Issue by Wangws1004** [MohamedHamdy28/Traffic-violation-detection-system#1]
I can't proceed to step "Place your video file in the "data" folder." and "Run the system using the main.py script with the following arguments" in "Usage".

The location of the 'data' folder is unknown because the .gitignore file contains a 'data' folder. Also, the existence of the 'dataloaders.py' file inside the 'data' folder is unknown.

And in the 24th line of the file "main.py ,"
parser.add_argument("VIDEO_PATH", type=str)
Please check if,
parser.add_argument ("--VIDEO_PATH", type=str) is correct.

I hope you can resolve the above issues.

**Comment by MohamedHamdy28** [comment]
Hello,

Thank you for reporting this issue. I have updated the code and added the data folder. You should include the video that you want to analyze in the data folder.

Also you need to download the models folder and include it in the directory from here: https://drive.google.com/drive/folders/1qr7XjXTiWHyrw1bybSrcqc0eNAAeK2M5?usp=sharing

Please let me know if you are still facing problems running the repo.
